### ISSUE TITLE
获取调用方地址有点问题

### ISSUE THREAD

**Issue by sunl888** [Zuofw/zuofw-rpc#1]
我看到代码里好像并没有利用zk的服务发现功能获取调用方地址，而是直接用`LocalRegistry` 获取的调用地址，这是不是有问题呀？<img width="903" alt="截屏2024-09-23 20 20 45" src="https://github.com/user-attachments/assets/4804c3aa-4db4-49c5-b63a-6f5739f848d3">

**Comment by Zuofw** [comment]
如你所见，在provider启动类这里已经将服务注册到本地和远程zk了，而你给出的那个地方是provider的Handler，里面当然是可以使用本地直接获取
![image](https://github.com/user-attachments/assets/7b2f6485-fa8e-4089-b336-8ac45d879727)

而消费端这里是在这里获取的
![image](https://github.com/user-attachments/assets/4879368b-b94a-48ac-b625-602c2f2e2b02)

**Comment by sunl888** [comment]
哦哦，好滴好滴，了解了，继续啃其他的知识点去
